spring.application.name=darkhusky_back

server.port=8081

# BASE DE DATOS POSTGRESQL

# Configuración de PostgreSQL

spring.datasource.url=jdbc:postgresql://localhost:5432/darkhusky_sql_21_08_25
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Cambiar la ruta de Swagger UI (por defecto /swagger-ui.html)
springdoc.swagger-ui.path=/doc

# CLOUDFLARE R2

cloudflare.r2.accessKey=e36be399bbdc1af5585dc756309874e6
cloudflare.r2.secretKey=b9920bc6e4c26274200fc6f081c1cb6e30cd487d0097289defc5911e297b1302
cloudflare.r2.bucket=imagenespruebasdarkhusky
cloudflare.r2.endpoint=https://6d5fa79ff88e15fc726f458e67666b66.r2.cloudflarestorage.com
cloudflare.r2.region=us-east-1
cloudflare.r2.presignDurationMinutes=600

